version: "2"

services:
  app:
    container_name: nodeapp
    command: nodemon -L 
    build: ./
    volumes:
     - ".:/usr/src/app"
     - "./usr/src/app/node_modules"
    ports:
      - "8080:8080"
    